function shuffle(array) {
  var currentIndex = array.length, temporaryValue, randomIndex;
  while (0 !== currentIndex) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex -= 1;
    temporaryValue = array[currentIndex];
    array[currentIndex] = array[randomIndex];
    array[randomIndex] = temporaryValue;
  }
  return array;
}

var array_definitions = [
  ["Moment of inertia", "is a measure of how much an object resists a change in angular velocity."],
  ["Torque", "when a force (or couple) causes an object to turn, the turning effect is known as torque."],
  ["Angular momentum", "when no external force is applied (torque/friction) the total angular momentum of a system remains constant."],
  ["Angular impulse", "is the change in angular momentum."],
  ["Isothermal", "an isothermal process is one in which the temperature of the system remains constant. ΔU=0 Q=W"],
  ["Adiabatic", "an adiabatic process is one in which no heat is gained or lost by the system. Q=0 ΔU=-W"],
  ["Changes at constant pressure", "W=pΔV"],
  ["Changes at constant volume", "work done is zero W=0 Q=ΔU"],
  ["Indicated Power", "the net work done per second by the cylinders in an engine. OR max theoretical power generated by the gases in the engine."],
  ["Refrigerators", "extract as much heat energy from the cold space."],
  ["Heat pumps", "aims to pump as much heat as possible into the heat space."],
  ["Coefficient of performance", "measure of how well this work is converted into heat transfer."],
];

var word = document.getElementById('word');
var definition = document.getElementById('definition');
var next_button = document.getElementById('next');
var back_button = document.getElementById('back');
var restart_button = document.getElementById('restart');
var show_button = document.getElementById('show');
var hide_button = document.getElementById('hide');
var number = 0;

function endFunction(){
  word.innerHTML =  "Finished";
  definition.innerHTML = "";
  next_button.style.display = "none";
  back_button.style.display = "block";
  restart_button.style.display = "block";
  hide_button.style.display = "none";
}

function backFunction() {
  location.href='definitions_physics.html';
}

function showFunction(){
  definition.innerHTML = array_definitions[number][1];
  next_button.style.display = "block";
  hide_button.style.display = "block";
  show_button.style.display = "none";
}

function hideFunction(){
  definition.innerHTML = "";
  hide_button.style.display = "none";
  next_button.style.display = "none";
  show_button.style.display = "block";
}

function nextFunction() {
  number += 1;
  if (array_definitions.length === number){
    endFunction();
  }else{
    word.innerHTML = array_definitions[number][0];
    definition.innerHTML = array_definitions[number][1];
  }
}

function restartFunction() {
  number = 0;
  shuffle(array_definitions);
  back_button.style.display = "none";
  restart_button.style.display = "none";
  next_button.style.display = "block";
  word.innerHTML = array_definitions[number][0];
  definition.innerHTML = array_definitions[number][1];
  hide_button.style.display = "block";
}

shuffle(array_definitions);
word.innerHTML = array_definitions[number][0];
definition.innerHTML = array_definitions[number][1];
back_button.style.display = "none";
restart_button.style.display = "none";
show_button.style.display = "none";
